//
//  HomeWorker.swift
//  StarWarsApp
//
//  Created by Ebubekir Sezer on 6.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
    
    var starWarsStore: StarWarsStoreProtocol
    
    init(starWarsStore: StarWarsStoreProtocol) {
        self.starWarsStore = starWarsStore
    }
  
    func getCharacters(completion: @escaping((_ response: Characters, _ error: StarWarsError?) -> Void)) {
        
        self.starWarsStore.getCharacters { (characters, error) in
            if error != nil {
                completion(Characters(count: 1, results: []), error)
            } else {
                completion(characters, nil)
            }
        }
    }
}
