//
//  HomeModels.swift
//  StarWarsApp
//
//  Created by Ebubekir Sezer on 6.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
  enum StarWars
  {
    struct Request
    {
    }
    struct Response
    {
        var characters: [StarWarsCharacter]
    }
    struct ViewModel
    {
        struct DisplayedCharacters {
            var name: String
            var birthYear: String
        }
        
        var displayedCharacters: [DisplayedCharacters]
    }
  }
}
